import React, { Component } from 'react';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";


import {
  faUser,
  faUserSlash,
  faLock,
  faSun,
  faMoon,
  faPlugCircleXmark,
  faHeartCrack,
  faCircleInfo,
  faGavel,
  faEye,
  faKeyboard,
  faMousePointer,
  faCheckCircle,
  faTimesCircle,
  faExclamationTriangle,
  faArrowUp,
  faArrowDown,
  faBook,
  faGift,
  faFloppyDisk,
  faBullseye,
  faSync,
  faPlug,
  faArrowRight,
  faTrophy,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faUniversalAccess,
  faTerminal,
  faRocket,
  faExpand,
  faDesktop,
  faShieldAlt,
  faCookie,
  faCheck,
  faTimes,
  faInfoCircle,
  faKey,
  faServer,
  faCode,
  faPlay,
  faMailBulk,
  faTools,
  faBrain,
  faMobile,
  faCertificate,
  faUserGraduate,
  faDatabase,
  faCogs,
  faHardHat,
  faLanguage,
  faPalette,
  faNetworkWired,
  faGraduationCap,
  faSearch,
  faMicrochip,
  faHome,
  faCompass,
  faArrowLeft } from


'@fortawesome/free-solid-svg-icons';

import {
  faGithub,
  faLinkedin,
  faPython,
  faJs,
  faJava,
  faReact,
  faNodeJs } from
'@fortawesome/free-brands-svg-icons';


export const Icons = ({ icon, size, color, className, spin }) => {

  return <FontAwesomeIcon icon={icon} size={size} color={color} className={className} spin={spin} />;

};


export {
  faUser,
  faUserSlash,
  faLock,
  faSun,
  faMoon,
  faPlugCircleXmark,
  faHeartCrack,
  faCircleInfo,
  faGavel,
  faEye,
  faKeyboard,
  faMousePointer,
  faCheckCircle,
  faTimesCircle,
  faExclamationTriangle,
  faArrowUp,
  faArrowDown,
  faGithub,
  faLinkedin,
  faBook,
  faGift,
  faFloppyDisk,
  faBullseye,
  faSync,
  faPlug,
  faArrowRight,
  faTrophy,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faUniversalAccess,
  faTerminal,
  faRocket,
  faExpand,
  faDesktop,
  faShieldAlt,
  faCookie,
  faCheck,
  faTimes,
  faInfoCircle,
  faKey,
  faServer,
  faCode,
  faPlay,
  faMailBulk,
  faTools,
  faBrain,
  faMobile,
  faCertificate,
  faUserGraduate,
  faPython,
  faJs,
  faJava,
  faReact,
  faDatabase,
  faCogs,
  faHardHat,
  faLanguage,
  faPalette,
  faNetworkWired,
  faGraduationCap,
  faSearch,
  faNodeJs,
  faMicrochip,
  faHome,
  faCompass,
  faArrowLeft };